### ISSUE TITLE
Bug: 1.1.0 throws error on calling getKindeSession on unauthenticated user 

### ISSUE THREAD

**Issue by jonhester** [kinde-oss/kinde-remix-sdk#18]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

Can be duplicated by just protecting a route as per https://docs.kinde.com/developer-tools/sdks/backend/remix-sdk/#protect-routes. It is not an issue in 1.0.4 so pinning to that for now.

```
Error: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Refresh token provided is malformed.
    at AuthorizationCode.<anonymous> (file:///Users/jon/code/customer-portal/node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/oauth2-flows/AuthCodeAbstract.js:315:31)
    at step (file:///Users/jon/code/customer-portal/node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/oauth2-flows/AuthCodeAbstract.js:43:23)
    at Object.next (file:///Users/jon/code/customer-portal/node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/oauth2-flows/AuthCodeAbstract.js:24:53)
    at fulfilled (file:///Users/jon/code/customer-portal/node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/oauth2-flows/AuthCodeAbstract.js:15:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Library URL

https://github.com/kinde-oss/kinde-remix-sdk

### Library version

1.1.0

### Operating system(s)

macOS

### Operating system version(s)

macOS Sonoma 14.4

**Comment by peterphanouvong** [comment]
thanks for raising this @jonhester, we'll fix this up :)

**Comment by peterphanouvong** [comment]
Hey @jonhester unfortunately I haven't been able to recreate this issue on 1.1.1. Would you be able to share any more info that might help us debug?
